
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css # for main css
stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css # for toc basic style

# scripts loaded in the end of the body
scripts_defer:
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.min.js #for toc
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script
- /js/toc.js # for toc render


social:
  Github: https://github.com/yours
  Codepen: https://codepen.io/yours
  Dribbble: https://dribbble.com/yours
  Twitter: https://twitter.com/yours
  知乎: https://www.zhihu.com/people/yours
  掘金: https://juejin.im/user/yours
  Mail: tomail:xxx@yourmail.xxxx
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: UA-151544816-1
